name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-code-coverage
      
    - name: Read codecov-path
      run: |
          export CODECOV_JSON_PATH=$(swift test --show-codecov-path)
          echo "CODECOV_JSON_PATH=$CODECOV_JSON_PATH"
          echo "GITHUB_WORKSPACE=${{ env.GITHUB_WORKSPACE }}"
          echo "::set-env name=CODECOV_JSON_PATH::$CODECOV_JSON_PATH"
          perl -pi.bak -e 's#${{ env.GITHUB_WORKSPACE }}/##g' $CODECOV_JSON_PATH
          
    - name: Upload code coverage
      uses: actions/upload-artifact@v1
      with:
        name: ISO639-codecov
        path: ${{ env.CODECOV_JSON_PATH }}
        
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ${{ env.CODECOV_JSON_PATH }}
        fail_ci_if_error: false
      
