name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: make build

    - name: Run tests
      run: make test-all
                
    - name: Upload code coverage
      uses: actions/upload-artifact@v1
      with:
        name: ISO639-codecov
        path: ${{ env.CODECOV_JSON_PATH }}
        
    - name: Codecov
      run: make upload_to_codecov
      